import { Application } from "../models/Application.model";

export const APPLICATIONS: Application[] = [
  {
    name: "Order in the Court",
    link: "https://order-in-the-court-app.herokuapp.com/",
    description: "A free browser-based improv game loosely based off of reality court shows.",
    icon: "fa-gavel",
    status: 1,
  },
  {
    name: "Zoom Backgrounds",
    link: "https://zoom-backgrounds.herokuapp.com/",
    description: "A showcase for some Zoom Backgrounds.",
    icon: "fa-picture-o",
    status: 1,
  },
  {
    name: "XPath Assitant",
    link: "https://xpath-assistant.herokuapp.com/",
    description: "A simple app to help building XPath statements.",
    icon: "fa-map-signs",
    status: 1,
  },
  {
    name: "User Management",
    link: "https://aoti-user-management-ui.herokuapp.com/",
    description: "User Management for most of my applications.",
    icon: "fa-users",
    status: 1,
  },
  {
    name: "Adam in the Parking Lot",
    link: "http://www.adamintheparkinglot.com/",
    description: "Coming soon: website for my band.",
    icon: "fa-music",
    status: 3,
  },
  {
    name: "Basic Angular App",
    link: "https://aoti-basic-angular-app.herokuapp.com/",
    description: "A sample Angular App without any style or real use.",
    icon: "fa-laptop",
    status: 1,
  },
  {
    name: "Adam on the Internet",
    link: "http://adamontheinternet.com/",
    description: "My main website.",
    icon: "fa-home",
    status: 1,
  },
  {
    name: "Callanan Concepts",
    link: "http://callananconcepts.club/",
    description: "Old Version of my main website.",
    icon: "fa-home",
    status: 3,
  },
  {
    name: "Overton Portfolio (Sample Site)",
    link: "https://overton-portfolio-ui.herokuapp.com/",
    description: "A site I started building for a friend's portfolio.",
    icon: "fa-id-badge",
    status: 1,
  },
  {
    name: "Armor Equipment (Small Business Site)",
    link: "http://www.armor-equip.com/",
    description: "A website for a small business that sells trash equipment that I built right out of college.",
    icon: "fa-trash",
    status: 1,
  },
  {
    name: "Fake Fan Adam",
    link: "https://fake-fan-adam.herokuapp.com/",
    description: "My personal home page.",
    icon: "fa-star",
    status: 3,
  },
  {
    name: "Basic Express App",
    link: "https://aoti-basic-express-app.herokuapp.com/",
    description: "A basic Express App I use for a backend. Connects to a cloud MongoDB database.",
    icon: "fa-laptop",
    status: 3,
  },
  {
    name: "Adam on the Internet (new)",
    link: "https://adam-on-the-internet.herokuapp.com/",
    description: "My professional home page.",
    icon: "fa-home",
    status: 3,
  },
  {
    name: "Story Dice",
    link: "https://story-dice.herokuapp.com/",
    description: "An app I made early on that simulates dice rolls with random images.",
    icon: "fa-question-circle",
    status: 1,
  },
  {
    name: "Adam in the Parking Lot: Backdrop",
    link: "https://parking-lot-screen.herokuapp.com/",
    description: "An app I made as a backdrop for when my band plays shows.",
    icon: "fa-film",
    status: 3,
  },
];
